### ISSUE TITLE
Опечатки в _posts/2014-03-18-interview-questions.md

### ISSUE THREAD

**Issue by ypypy28** [amezhenin/amezhenin.github.io#2]
> Подробнее об **_это_**
* этом

> в различным московских **_копаниях_**
* компаниях

> Очень хороша статья на PyPix: Metaprogramming in Python

Ссылка умерла, есть в [вебархиве](http://web.archive.org/web/20140210000523/http://pypix.com/python/metaprogramming-python/)

> могу порекомендовать эту статью.

Ссылка умерла, есть в [вебархиве](http://web.archive.org/web/20131227024144/http://pypix.com/python/advanced-data-structures-python/)

> **_Сам_** я только пару раз **_использовала_**
* Либо сама, либо использовал

> ведь **_на_** каждый день интересуются
* не

**Comment by amezhenin** [comment]
Спасибо за ссылки на вебархив :+1: . Все исправил.
